### ISSUE TITLE
/opt/python/bin/pip: No such file or directory

### ISSUE THREAD

**Issue by ddavidebor** [dit4c/dockerfile-dit4c-container-jupyterlab#2]
Hi, 

I tried building the container out of curiosity with

`docker build -t dit4c-container-jupyterlab .
`

and i got 

`/opt/python/bin/pip: No such file or directory`

Davide

**Comment by tjdett** [comment]
@ddavidebor Thanks for letting me know. I've updated it so it works with the latest base image.
